// <auto-generated />
using ImageGalleryApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImageGalleryApi.Migrations
{
    [DbContext(typeof(ImageGalleryApiContext))]
    [Migration("20230518013156_TestImg")]
    partial class TestImg
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ImageGalleryApi.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Available")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Color1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Color2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Color3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ImageId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ImageId = 1,
                            Available = true,
                            Color1 = "Red",
                            Color2 = "White",
                            Color3 = "Orange",
                            Date = "1/1/2000",
                            Description = "Test Landscape Painting",
                            ImageUrl = "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png",
                            Medium = "Acrylic and Mixed media on Canvas",
                            Size = "24in x 36in",
                            Subject = "Landscape",
                            Title = "Test1"
                        },
                        new
                        {
                            ImageId = 2,
                            Available = true,
                            Color1 = "Green",
                            Color2 = "White",
                            Color3 = "Blue",
                            Date = "1/1/2000",
                            Description = "Test Portait Painting",
                            ImageUrl = "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png",
                            Medium = "Acrylic and Mixed media on Canvas",
                            Size = "24in x 24in",
                            Subject = "Portait",
                            Title = "Test2"
                        },
                        new
                        {
                            ImageId = 3,
                            Available = true,
                            Color1 = "Red",
                            Color2 = "Black",
                            Color3 = "Blue",
                            Date = "1/1/2000",
                            Description = "Test Portrait Relief Print",
                            ImageUrl = "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png",
                            Medium = "Linoleum cut ink print on paper",
                            Size = "8in x 10in",
                            Subject = "Portait",
                            Title = "Test3"
                        },
                        new
                        {
                            ImageId = 4,
                            Available = true,
                            Color1 = "Orange",
                            Color2 = "Black",
                            Color3 = "Blue",
                            Date = "1/1/2000",
                            Description = "Test Landscape Relief Print",
                            ImageUrl = "https://www.dropbox.com/s/v92tzxbk8m1tvb6/art-gallery-diagram.png?dl=0",
                            Medium = "Linoleum cut ink print on paper",
                            Size = "12in x 9in",
                            Subject = "Landscape",
                            Title = "Test4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
